version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    env_file:
      - db.env
    volumes:
      - "./db/db_data:/var/lib/mysql"
      - "./db/setup_db.sh:/code/setup_db.sh"

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: flask_app
    restart: always
    env_file:
      - app.env
    working_dir: /code/app
    volumes:
      - "./app:/code/app"
    command: gunicorn -w 1 -b :8000 wsgi
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: nginx_web
    restart: always
    volumes:
      - ./web/app.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/static
      - ./web/access.log:/var/log/access.log
      - ./web/error.log:/var/log/error.log
    ports:
      - "80:80"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - app
